In [52]:
##Adds the path to the codes
import os
import sys

path_common="/home/jkipen/ProtInfGPU/code/";
sys.path.append(path_common) #Adds common path to import the python files

In [53]:
from ProteinInferenceEMv2 import ProteinInferenceEMv2
import numpy as np
import pandas as pd
import time

path_5_prot="/home/jkipen/raid_storage/ProtInfGPU/data/5_Prot/"


In [54]:
PIEM=ProteinInferenceEMv2(path_5_prot+"numpy/Common/df_info.csv")



# Veryfing P(X/I) calculation
First we compute this calculation with the code that we have been using for a while, which we know we can trust

## Calc of true result


In [63]:
#Loading scores from RF_10_10 results
data = np.load(path_5_prot + "numpy/rf_n_est_10_depth_10/Common/Scores_0.npz");
top_n_flu_scores = data["top_n_flu_scores"]
top_n_flu_iz = data["top_n_flu_iz"]
#Lets keep only 1000 reads, since for higher proteins we will use a few amount of reads in each compute too
top_n_flu_scores=top_n_flu_scores[:1000,:]; 
top_n_flu_iz=top_n_flu_iz[:1000,:]; 
#Generate sparse matrix
S, p_rem = PIEM.build_sparse_matrix_N_Best(top_n_flu_scores, top_n_flu_iz, N=30) #N=30 was good for this dataset


In [64]:
n_runs=100; #Run many times to have a good time estimate.
ts=[];
for i in range(n_runs):
    t_start=time.time()
    P_X_given_I_rel = PIEM.get_P_X_given_I_rel_sparse(S, p_rem)
    ts.append(time.time()-t_start)

print("Avg runtime on CPU: " + str(np.mean(ts)));
np.save("True_P_X_given_I_rel.npy",P_X_given_I_rel)

Avg runtime on CPU: 0.0016411495208740233


## Tools to compare results
Func to test difference in values

In [17]:
def stats_diff(true_mat,comp_mat):
    diff_abs=np.abs(comp_mat-true_mat);
    mae=np.mean(diff_abs, axis = None)
    max_err=np.max(diff_abs, axis = None)
    idx_max=diff_abs.argmax();
    print("The MAE was " + str(mae) + " and the max error is  " + str(max_err) + " and was at index " + str(idx_max))
    print("The max err index had "  + str(true_mat.flatten()[idx_max])+ " in the original, but " +str(comp_mat.flatten()[idx_max]) +" in the other matrix")
    

In [18]:
random_guess=np.random.normal(size=np.shape(P_X_given_I_rel))
stats_diff(P_X_given_I_rel,random_guess)

The MAE was 0.8051492915059574 and the max error is  3.6314076041403314 and was at index 913
The max err index had 0.0009243632666766644 in the original, but 3.632331967407008 in the other matrix


Exporting the arrays needed for a cuda code to reproduce this on its own:

In [34]:
def save_array_to_csv(arr,file_name):
    df = pd.DataFrame(arr)
    df.to_csv("RepVars/"+file_name, header=False, index=False)

def export_p_flu_e_given_I(p_fe_g_I):
    n_prots=np.shape(p_fe_g_I)[0]
    n_fe=np.shape(p_fe_g_I)[1]
    p_fe_for_I_all=[]
    p_fe_for_I_iz_fe_all=[]
    n_fe_per_I=[]
    for i in range(n_prots):
        p_fe_for_I=[] #List containing the probs for a given protein'
        p_fe_for_I_iz_fe=[] #List containing the index of the flu
        for j in range(n_fe):
            if p_fe_g_I[i,j]!=0:
                p_fe_for_I.append(p_fe_g_I[i,j]);p_fe_for_I_iz_fe.append(j);
        p_fe_for_I_all.append(p_fe_for_I);
        p_fe_for_I_iz_fe_all.append(p_fe_for_I_iz_fe);
        n_fe_per_I.append(len(p_fe_for_I));
    return p_fe_for_I_all,p_fe_for_I_iz_fe_all,n_fe_per_I;



In [37]:
p_fe_for_I_all,p_fe_for_I_iz_fe_all,n_fe_per_I=export_p_flu_e_given_I(PIEM.P_flu_exp_given_prot_i)
save_array_to_csv(top_n_flu_scores[:,:30],"top_n_flu_scores.csv")
save_array_to_csv(top_n_flu_iz[:,:30],"top_n_flu_iz.csv")
save_array_to_csv(np.concatenate(p_fe_for_I_all),"p_fe_for_I_all.csv")
save_array_to_csv(np.concatenate(p_fe_for_I_iz_fe_all),"p_fe_for_I_iz_fe_all.csv")
save_array_to_csv(np.array(n_fe_per_I),"n_fe_per_I.csv")

### Checking the values of perr

In [68]:
a=pd.read_csv("/home/jkipen/ProtInfGPU/dev/P_X_giv_I_rel_w_GPU/RepVars/top_n_flu_scores.csv", header=None)
arr=a.to_numpy()
print(1-np.sum(arr,axis=1))

[0.11462108 0.13432996 0.10955538 0.13663985 0.17435065 0.13028822
 0.11620884 0.11507193 0.10955538 0.11620884 0.13617524 0.110943
 0.13663985 0.10955538 0.13277395 0.15864031 0.110943   0.110943
 0.10955538 0.13028822 0.110943   0.1100159  0.13663985 0.12999948
 0.15619862 0.13663985 0.11914184 0.17915703 0.15068408 0.12975835
 0.11462108 0.13617524 0.11620884 0.11620884 0.11620884 0.13663985
 0.11620884 0.11507193 0.13663985 0.12999948 0.11620884 0.09954181
 0.11507193 0.12999948 0.13432996 0.11575443 0.11507193 0.16580027
 0.11620884 0.110943   0.13617524 0.13663985 0.110943   0.13617524
 0.11620884 0.11620884 0.11388358 0.1321612  0.11620884 0.1030904
 0.11620884 0.110943   0.11620884 0.13663985 0.110943   0.110943
 0.11620884 0.12999948 0.13617524 0.13028822 0.10477305 0.13663985
 0.1321612  0.110943   0.13663985 0.13028822 0.1182056  0.13663985
 0.13003367 0.110943   0.13663985 0.13663985 0.13028822 0.1321612
 0.13663985 0.1755564  0.110943   0.11620884 0.110943   0.10955538
 0.

In [75]:
P_X_g_I_rel=np.load("True_P_X_given_I_rel.npy")

In [74]:
save_array_to_csv(a,"True_P_X_given_I_rel.csv")

In [76]:
P_X_g_I_rel

array([[0.00586462, 0.00431406, 0.00224528, 0.00092436, 0.0061128 ],
       [0.00599161, 0.00494558, 0.00326926, 0.00108331, 0.00612963],
       [0.00584636, 0.00433247, 0.00246766, 0.00088351, 0.00613222],
       ...,
       [0.00760891, 0.00353664, 0.00930593, 0.00303117, 0.00371086],
       [0.00613484, 0.0020217 , 0.00434038, 0.00151186, 0.00946557],
       [0.00548734, 0.00443105, 0.0046002 , 0.00287341, 0.01452314]])

In [80]:
p_prot_est=np.ones(5)/5;
P_X_I_rel=P_X_g_I_rel*p_prot_est
P_X_I_rel

array([[0.00117292, 0.00086281, 0.00044906, 0.00018487, 0.00122256],
       [0.00119832, 0.00098912, 0.00065385, 0.00021666, 0.00122593],
       [0.00116927, 0.00086649, 0.00049353, 0.0001767 , 0.00122644],
       ...,
       [0.00152178, 0.00070733, 0.00186119, 0.00060623, 0.00074217],
       [0.00122697, 0.00040434, 0.00086808, 0.00030237, 0.00189311],
       [0.00109747, 0.00088621, 0.00092004, 0.00057468, 0.00290463]])

In [84]:
norm_factors=np.sum(P_X_I_rel,axis=1);
print(norm_factors)

[0.00389222 0.00428388 0.00393244 0.00440031 0.00512729 0.00433269
 0.00400078 0.00405059 0.00393244 0.00400078 0.00441194 0.00395634
 0.00440031 0.00393244 0.00430488 0.00450443 0.00395634 0.00395634
 0.00393244 0.00433269 0.00395634 0.0038497  0.00440031 0.00420629
 0.00473571 0.00440031 0.00402948 0.00424746 0.00478194 0.00431957
 0.00389222 0.00441194 0.00400078 0.00400078 0.00400078 0.00440031
 0.00400078 0.00405059 0.00440031 0.00420629 0.00400078 0.00413579
 0.00405059 0.00420629 0.00428388 0.00376762 0.00405059 0.00516584
 0.00400078 0.00395634 0.00441194 0.00440031 0.00395634 0.00441194
 0.00400078 0.00400078 0.00380439 0.00432173 0.00400078 0.00382087
 0.00400078 0.00395634 0.00400078 0.00440031 0.00395634 0.00395634
 0.00400078 0.00420629 0.00441194 0.00433269 0.00378063 0.00440031
 0.00432173 0.00395634 0.00440031 0.00433269 0.00387289 0.00440031
 0.00421195 0.00395634 0.00440031 0.00440031 0.00433269 0.00432173
 0.00440031 0.00494773 0.00395634 0.00400078 0.00395634 0.0039

In [86]:
alphas=(P_X_I_rel.T/norm_factors).T
alphas

array([[0.30135066, 0.22167571, 0.11537278, 0.04749794, 0.31410291],
       [0.27972826, 0.23089268, 0.15263092, 0.05057598, 0.28617216],
       [0.29733983, 0.22034478, 0.12550265, 0.04493444, 0.3118783 ],
       ...,
       [0.2798061 , 0.13005453, 0.34221162, 0.11146653, 0.13646122],
       [0.26134241, 0.08612391, 0.18489898, 0.06440457, 0.40323013],
       [0.17193535, 0.13883841, 0.1441385 , 0.09003282, 0.45505493]])

In [87]:
np.sum(alphas,axis=0)

array([261.52794599, 195.42915567, 248.66309325,  75.65844398,
       218.72136112])